# Generated by Django 3.2.6 on 2022-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=55)),
                ('last_name', models.CharField(default='', max_length=55)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
