# Generated by Django 3.2.6 on 2022-04-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_Name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=75)),
                ('destination', models.CharField(max_length=75)),
                ('Nos', models.IntegerField()),
                ('rem', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
