# Generated by Django 3.2.6 on 2022-04-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_Name', models.CharField(max_length=50)),
                ('No_Seats', models.IntegerField()),
                ('Contact', models.CharField(max_length=15)),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('Price_Per_Ticket', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('T_date', models.CharField(max_length=15)),
                ('T_time', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
