# Generated by Django 3.2.6 on 2022-04-02 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_Date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
